/* ===================================================================
   preload.js — every asset fetched behind the start button
   -------------------------------------------------------------------
   The start button does not appear until all of it is local. Until
   then a themed bar sits in the button's place and shows real progress.

   FIVE THINGS THAT MATTER HERE

   1. BYTES, NOT FILE COUNTS. Progress is read from a streaming reader,
      so the bar moves smoothly through the 3.5MB music track instead of
      jumping one-ninth at a time. Weights come from the real on-disk
      sizes (tools/sizes.py generates the table) and are refined by
      Content-Length when the server sends one.

   2. SMALLEST FIRST. Sorted by weight, so every image — the whole
      visual world — has landed by 15% and the music, which is 75% of
      the payload on its own, can never starve the start screen.

   3. NOTHING CAN BLOCK. A failure, a stall, an abort, or file:// where
      fetch is not allowed all count as DONE and leave the element on
      its original URL. There is a stall timeout per transfer rather
      than a size-based one: "no bytes for 10 seconds" is the condition
      that actually means trouble, and it does not need tuning per file.

   4. BLOB SWAP, WITH A WAY BACK. A fetched asset is handed to its
      element as a blob: URL so "loaded" means local. Each swapped
      element gets a one-time error handler that restores the file URL
      (and resumes playback for media) — a blob that the browser refuses
      must never cost the player the asset.

   5. THE BAR ONLY EVER GOES FORWARD. Refining a weight mid-flight can
      lower the true percentage, so the reported value is clamped to its
      own maximum.
   =================================================================== */
window.CG = window.CG || {};

CG.Preload = (function () {
  'use strict';

  var SIZES = {
    'assets/airplane.webp': 17552,
    'sfx/airplane%20reached%20sound%20.ogg': 20491,
    'assets/background.webp': 81552,
    'assets/start%20button.webp': 85718,
    'assets/runway%20.webp': 147188,
    'assets/mountain.webp': 157124,
    'assets/start%20screen.webp': 202196,
    'sfx/airplane%20fly%20sound%20.ogg': 464279,
    'sfx/bg%20music.ogg': 3503142,
  };
  /* 9 files, 4679242 bytes (4.46 MB) — generated by tools/sizes.py */

  var CONCURRENCY = 5;
  var STALL_MS    = 10000;   /* no bytes for this long -> give up on it   */
  var HARD_MS     = 60000;   /* and never wait longer than this, ever     */

  var state = {
    started: false,
    done: false,
    pct: 0,
    missing: [],
    blobs: {},
    bytes: {},
    aborts: []
  };

  /* ---- URL matching ------------------------------------------------
     The filenames contain spaces, so markup carries %20 and the size
     table does too. Compare decoded, and only on the tail, so a page
     served from a sub-path still matches. */
  function decodeSafe(u) {
    try { return decodeURIComponent(u); } catch (e) { return u; }
  }
  function sameAsset(elSrc, key) {
    if (!elSrc) return false;
    var a = decodeSafe(elSrc), b = decodeSafe(key);
    return a === b || a.slice(-b.length) === b;
  }
  function elementsFor(key) {
    var out = [], i;
    /* data-src: images that have NOT started their own request.
       src: the audio elements, which carry preload="none" and so have
       not started one either. */
    var all = document.querySelectorAll('img[data-src], img[src], audio[src], video[src]');
    for (i = 0; i < all.length; i++) {
      var el = all[i];
      var u = el.getAttribute('data-src') || el.getAttribute('src');
      if (sameAsset(u, key)) out.push(el);
    }
    return out;
  }
  function originalOf(el) {
    return el.getAttribute('data-src') || el.getAttribute('src');
  }

  /* ---- the blob swap, and the way back ----------------------------- */
  function swap(key, blob) {
    var url = URL.createObjectURL(blob);
    state.blobs[key] = url;
    state.bytes[key] = blob.size;      /* checked against SIZES by the browser test */
    elementsFor(key).forEach(function (el) {
      var original = originalOf(el);
      var playing = !el.paused && el.currentTime > 0;
      /* one-time: a blob the browser will not decode must not cost the
         player the asset, so put the file URL back and carry on */
      el.addEventListener('error', function once() {
        el.removeEventListener('error', once);
        if (el.getAttribute('src') !== original) {
          el.setAttribute('src', original);
          if (typeof el.play === 'function' && playing) {
            try { el.load(); var p = el.play(); if (p && p.catch) p.catch(function () {}); }
            catch (e) { /* nothing more to try */ }
          }
        }
      });
      el.setAttribute('src', url);
      if (typeof el.load === 'function') { try { el.load(); } catch (e) {} }
    });
  }

  /* ---- one transfer ------------------------------------------------ */
  function fetchOne(key, weight, onBytes) {
    return new Promise(function (resolve) {
      var settled = false, got = 0, stall = null, hard = null;
      var ctl = (typeof AbortController === 'function') ? new AbortController() : null;

      function finish(ok) {
        if (settled) return;
        settled = true;
        if (stall) window.clearTimeout(stall);
        if (hard) window.clearTimeout(hard);
        /* whatever happened, this asset is accounted for in full: the
           bar must reach 100% even when the network does not cooperate */
        onBytes(key, weight, true);
        if (!ok) {
          state.missing.push(key);
          /* THE FAILURE PATH STILL HAS TO PRODUCE A PICTURE. The element
             never started its own request, so falling back means handing
             it the plain file URL and letting the browser try normally. */
          elementsFor(key).forEach(function (el) {
            if (!el.getAttribute('src')) el.setAttribute('src', originalOf(el));
          });
        }
        resolve(ok);
      }
      function armStall() {
        if (stall) window.clearTimeout(stall);
        stall = window.setTimeout(function () {
          state.aborts.push(key + ' (stall)');
          if (ctl) { try { ctl.abort(); } catch (e) {} }
          finish(false);
        }, STALL_MS);
      }

      if (typeof fetch !== 'function') { finish(false); return; }
      hard = window.setTimeout(function () {
        state.aborts.push(key + ' (hard cap)');
        if (ctl) { try { ctl.abort(); } catch (e) {} }
        finish(false);
      }, HARD_MS);
      armStall();

      var opts = ctl ? { signal: ctl.signal, cache: 'force-cache' } : { cache: 'force-cache' };
      var req;
      try { req = fetch(key, opts); } catch (e) { finish(false); return; }

      req.then(function (res) {
        if (!res || !res.ok) { finish(false); return; }
        /* Content-Length is more authoritative than the table */
        var cl = parseInt(res.headers.get('content-length') || '', 10);
        if (isFinite(cl) && cl > 0) { weight = cl; onBytes(key, 0, false, cl); }

        if (!res.body || typeof res.body.getReader !== 'function') {
          /* no streaming here — still correct, just coarser */
          return res.blob().then(function (b) {
            got = b.size; onBytes(key, got, false);
            swap(key, b); finish(true);
          });
        }
        var reader = res.body.getReader(), chunks = [];
        return (function pump() {
          return reader.read().then(function (r) {
            if (r.done) {
              swap(key, new Blob(chunks));
              finish(true);
              return;
            }
            chunks.push(r.value);
            got += r.value.length;
            armStall();
            onBytes(key, got, false);
            return pump();
          });
        })();
      }).catch(function () { finish(false); });
    });
  }

  /* ---- the queue ---------------------------------------------------
     Smallest-first, EXCEPT that the two start-screen files go first
     regardless of size. Pure smallest-first put the start art seventh:
     on a throttled link that is several seconds of gauge on a bare
     background. The spec's reason for smallest-first is that visible art
     must not be starved behind the big files — promoting the art that is
     visible RIGHT NOW serves that reason better than the rule does. */
  var FIRST = ['assets/start%20screen.webp', 'assets/start%20button.webp'];
  function queue() {
    var rest = Object.keys(SIZES).filter(function (k) { return FIRST.indexOf(k) === -1; });
    rest.sort(function (a, b) { return SIZES[a] - SIZES[b]; });
    return FIRST.filter(function (k) { return k in SIZES; }).concat(rest);
  }

  /* ---- the run ----------------------------------------------------- */
  function run(onProgress) {
    if (state.started) return state.promise;
    state.started = true;

    var keys = queue();
    var weight = {}, loaded = {}, complete = {};
    keys.forEach(function (k) { weight[k] = SIZES[k]; loaded[k] = 0; complete[k] = false; });

    var report = function () {
      var tot = 0, has = 0, k;
      for (k in weight) { tot += weight[k]; has += complete[k] ? weight[k] : Math.min(loaded[k], weight[k]); }
      var pct = tot ? (has / tot) * 100 : 100;
      if (pct > state.pct) state.pct = pct;        /* monotonic */
      if (onProgress) onProgress(state.pct);
    };

    var onBytes = function (k, bytes, isComplete, newWeight) {
      if (newWeight) weight[k] = newWeight;
      if (isComplete) { complete[k] = true; loaded[k] = weight[k]; }
      else if (bytes > loaded[k]) loaded[k] = bytes;
      report();
    };

    report();

    /* TWO PHASES, because being FIRST IN THE QUEUE IS NOT THE SAME AS
       BEING FIRST TO ARRIVE. With five lanes open, the start artwork
       shares the link with four other transfers and lands about a fifth
       of the way in — measured on a 900kbps link, the gauge read 16%
       with the title screen still blank. Given the whole pipe to itself
       it arrives in under two seconds.

       Total time barely moves (the link is the limit either way); what
       changes is that the screen the player is looking at fills up
       first, which is the entire reason the spec asks for smallest-first
       in the first place. */
    function drain(list, lanes) {
      var next = 0;
      function worker() {
        if (next >= list.length) return Promise.resolve();
        var k = list[next++];
        return fetchOne(k, weight[k], onBytes).then(worker);
      }
      var running = [];
      for (var i = 0; i < Math.min(lanes, list.length); i++) running.push(worker());
      return Promise.all(running);
    }

    var first = keys.filter(function (k) { return FIRST.indexOf(k) !== -1; });
    var rest  = keys.filter(function (k) { return FIRST.indexOf(k) === -1; });

    state.promise = drain(first, 2).then(function () {
      return drain(rest, CONCURRENCY);
    }).then(function () {
      state.done = true;
      state.pct = 100;
      if (onProgress) onProgress(100);
      return { missing: state.missing.slice() };
    });
    return state.promise;
  }

  return {
    run: run,
    isDone: function () { return state.done; },
    pct: function () { return state.pct; },
    missing: function () { return state.missing.slice(); },
    aborts: function () { return state.aborts.slice(); },
    /* byte counts actually received, per asset. The browser test compares
       these to SIZES: it is the only proof that a streamed fetch which
       Chrome reports as ERR_ABORTED still delivered every byte. */
    bytes: function () { var o = {}, k; for (k in state.bytes) o[k] = state.bytes[k]; return o; },
    /* exposed for the test harness and for tools/sizes.py to check */
    SIZES: SIZES,
    queueOrder: queue
  };
})();
