#!/usr/bin/env python3
"""Regenerate the preloader's size table from the files actually on disk.

    python3 tools/sizes.py            # print the block
    python3 tools/sizes.py --write    # splice it into js/preload.js

The preloader weights its progress bar by real byte counts, so a stale
table makes the bar lie. Re-run this after touching anything in assets/
or sfx/.
"""
import os, sys, urllib.parse, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHIPPED = ('.webp', '.ogg')

def table():
    rows = []
    for d in ('assets', 'sfx'):
        for f in sorted(os.listdir(os.path.join(ROOT, d))):
            if f.startswith('.') or not f.lower().endswith(SHIPPED):
                continue
            rows.append((d + '/' + urllib.parse.quote(f),
                         os.path.getsize(os.path.join(ROOT, d, f))))
    rows.sort(key=lambda t: t[1])          # smallest first: the queue order
    body = ['  var SIZES = {']
    for u, s in rows:
        body.append("    '%s': %d," % (u, s))
    body.append('  };')
    total = sum(s for _, s in rows)
    body.append('  /* %d files, %d bytes (%.2f MB) — generated by tools/sizes.py */'
                % (len(rows), total, total / 1048576))
    return '\n'.join(body), rows, total

def main():
    block, rows, total = table()
    if '--write' in sys.argv:
        p = os.path.join(ROOT, 'js', 'preload.js')
        s = open(p).read()
        pat = re.compile(r'  var SIZES = \{.*?\n  \};\n  /\*[^\n]*\*/', re.S)
        # assert on the MATCH, not on the text changing: an already-correct
        # table produces identical output, which is success and not failure
        assert pat.search(s), 'SIZES block not found in js/preload.js'
        new = pat.sub(lambda m: block, s, count=1)
        open(p, 'w').write(new)
        print('js/preload.js %s: %d files, %.2f MB'
              % ('updated' if new != s else 'already current', len(rows), total / 1048576))
    else:
        print(block)

if __name__ == '__main__':
    main()
